# state.py — Shared mutable state (breaks circular import between main.py, relay_vless.py and bot.py)
#
# POST-SQLITE MIGRATION NOTES
# ───────────────────────────
# SQLite (database.py, WAL mode) is now the SYSTEM OF RECORD. The dicts below
# are a hot read cache for per-connection work (relay lookups, subscription
# rendering) where a disk round-trip would be unacceptable.
#
# The asyncio.Lock objects here no longer coordinate PERSISTENCE (that moved to
# SQLite's single-writer discipline inside database.write_txn); they now guard
# only microsecond-scale read-modify-write cycles on the cache itself. They are
# uncontended in practice and cheaper than any cross-process alternative.
import asyncio
import threading
import collections
import hashlib
import hmac

# ── VLESS Relay State ──
RELAY_BUF = 256 * 1024   # 256 KB buffer
connections: dict = {}
sub_clients: dict = {}
TIMEOUT = 30

# ── Core State ──
stats = {
    "total_bytes": 0,
    "total_requests": 0,
    "total_errors": 0,
    "start_time": 0,
}

hourly_traffic = collections.defaultdict(int)
error_logs = collections.deque(maxlen=100)
LINKS: dict = {}
LINKS_LOCK = asyncio.Lock()

# ── Other shared locks/state ──
USERS_LOCK = asyncio.Lock()
SUBS_LOCK = asyncio.Lock()
SETTINGS_LOCK = asyncio.Lock()
SESSIONS_LOCK = asyncio.Lock()
GROUPS_LOCK = asyncio.Lock()
INBOUNDS: dict = {}  # inbound_id -> {name, protocol, port, network, security, domain, sni, external_port, fingerprint, reality_settings, xhttp_settings, created_at}
INBOUNDS_LOCK = asyncio.Lock()

# ── Path to UUID index (maps random paths like /abc123 to user/link UUIDs) ──
PATH_INDEX: dict = {}  # stripped_path -> {"uuid": str, "type": "user"|"link"}
PATH_INDEX_LOCK = asyncio.Lock()

IP_LOCK = threading.Lock()

# ══════════════════════════════════════════════════════════════════════════════
# Protocol registry — single source of truth shared by main.py / bot.py / edges.
# Xray-core native : vless (+xtls-vision flow), vmess, trojan, shadowsocks, reality
# Dual-core (sing-box): hysteria2, tuic — generated by generate_singbox_server_config()
# ══════════════════════════════════════════════════════════════════════════════
USER_PROTOCOLS = (
    "vless", "vmess", "trojan", "shadowsocks", "reality",
    "hysteria2", "tuic", "xtls-vision",
)
XTLS_VISION_FLOW = "xtls-rprx-vision"
UDP_PROTOCOLS = ("hysteria2", "tuic")          # served by sing-box (QUIC based)


def derive_proto_password(config_uuid: str, secret: str, salt: str) -> str:
    """Deterministic per-protocol password (Hysteria2 auth / TUIC v5 password).

    Derived from the user's config UUID + panel secret so it never needs to be
    stored or migrated; both master and edge nodes compute identical values.
    """
    return hmac.new(
        f"{salt}".encode(), f"{config_uuid}:{secret}".encode(), hashlib.sha256
    ).hexdigest()[:22]


# ══════════════════════════════════════════════════════════════════════════════
# Master–Edge (multi-node) state
# ══════════════════════════════════════════════════════════════════════════════
# node_id -> {name, token_hash, token_hint, status, last_seen, ip, version,
#             connections, cpu_percent, ram_percent, traffic_reported_bytes,
#             reports_count, created_at}
EDGES: dict = {}
EDGES_LOCK = asyncio.Lock()
# Monotonic revision bumped on every user/inbound change so edges can cheaply
# detect drift with a conditional pull (If-None-Match style).
EDGE_REVISION: int = 1

# Traffic deltas reported by edges, buffered here before being flushed into the
# user records by the master (batched under USERS_LOCK to stay thread-safe).
EDGE_TRAFFIC_QUEUE: collections.deque = collections.deque(maxlen=100_000)
EDGE_TRAFFIC_EVENT = None  # asyncio.Event, bound lazily to the running loop


def edge_token_hash(token: str) -> str:
    return hashlib.sha256(token.encode()).hexdigest()


def bump_edge_revision():
    global EDGE_REVISION
    EDGE_REVISION += 1
